version: "3.7"

services:
  core:
    container_name: core
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    restart: unless-stopped
    command: npm run dev
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4587:4587
